general:
  seed: 42
  algo: "ga"
  thread_number: 5

data:
  X: "Xtrain.tsv"
  y: "Ytrain.tsv"
  Xtest: "Xtest.tsv"
  ytest: "Ytest.tsv"
  pvalue_method: wilcoxon
  feature_minimal_prevalence_pct: 20 # per class, e.g. if any of the class reaches this level
  feature_maximal_pvalue: 0.5 # feature with differences less significant than this will be removed
  feature_minimal_feature_value: 0.0

ga:
  population_size: 1000
  max_epochs: 100
  min_epochs: 100
  max_age_best_model: 100
  kmin: 1
  kmax: 200 # do we keep it? 
  kpenalty: 0.001
  select_elite_pct: 25
  select_random_pct: 25
  mutated_children_pct: 100
  mutated_features_pct: 20
  mutation_non_null_chance_pct: 5
  feature_importance_permutations: 10
  keep_all_generations: false

cv:

