general:
  seed: 42
  algo: "ga"
  thread_number: 2

data:
  X: "samples/Qin2014/Xtrain.tsv"
  y: "samples/Qin2014/Ytrain.tsv"
  Xtest: "samples/Qin2014/Xtest.tsv"
  ytest: "samples/Qin2014/Ytest.tsv"
  pvalue_method: studentt
  feature_minimal_prevalence_pct: 10 # per class, e.g. if any of the class reaches this level
  feature_maximal_pvalue: 0.4 # feature with differences less significant than this will be removed
  feature_minimal_feature_value: 0.0001

ga:
  population_size: 1000
  max_epochs: 100
  min_epochs: 50
  max_age_best_model: 50
  #kmin: 1
  #kmax: 50 # do we keep it? 
  kpenalty: 0.001
  select_elite_pct: 25
  select_random_pct: 25
  mutated_children_pct: 100
  mutated_features_pct: 50
  mutation_non_null_chance_pct: 40
  feature_importance_permutations: 10